apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
        namespace: app-1-ns
    spec:
      containers:
      - name: app-1
        image: ovicious/laravel-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
      nodeName: "kind-control-plane"
