apiVersion: v1
kind: Service
metadata:
  labels:
    app: app1-service
  name: app1-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 9000-9000
    nodePort: 30090
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: app1-service
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
